### PR TITLE
Enable MongoDB service for CI testing

### PR DESCRIPTION
**Pull request by emmanvg**
Changes include:

- Enables Travis CI `mongodb` service.
- Installs `pymongo` only for CI tests.

This enhances overall code coverage, plus being able to test other backends.

### CODE REVIEW

**Comment by emmanvg** [comment]
There are some tests for `test_mongodb_backend` that look suspicious. For instance, the assertion of filter is passing in PY3 because it produces a generator and it is not evaluated...

**Comment by emmanvg** [comment]
Another problem is that even if we evaluate `[] is not None` returns `True`. Thus, making some tests pass. I am not clear on what we are testing here... 😕

**Comment by emmanvg** [comment]
The same applies to `test_memory_backend.py` where `filter()` is used.

**Comment by emmanvg** [comment]
@rpiazza, on [this](https://github.com/emmanvg/cti-taxii-server/blob/enable-mongo-testing/medallion/filters/mongodb_filter.py#L38) line. Why do we default to the latest version when `match_version` is None? I was looking at this [object_versioning](https://github.com/emmanvg/cti-taxii-server/blob/enable-mongo-testing/medallion/test/test_mongodb_backend.py#L143) test and it seems "versions" only has one entry because of this, instead of 5 or 6 because of the logic within lines 108-116.

**Comment by rpiazza** [comment]
From the TAXII spec - pg 21:

The version of the object(s) that are being requested. If no version parameter is provided, the server MUST return the latest version of the object.

last  - requests the latest version of an object. This is the default parameter value

**Comment by emmanvg** [comment]
Thanks for clarifying, we should be good to go then.

**Comment by rpiazza** [comment]
I think this comment is wrong:

https://github.com/emmanvg/cti-taxii-server/blob/3635f9050d5133a8dd58da79935ddf0958379e8f/medallion/test/test_mongodb_backend.py#L171

Otherwise - assuming it works - it looks good :-)

**Comment by emmanvg** [comment]
I have updated the comment @rpiazza mentioned. I will merge this PR then.

**Pull request merged**
