### PR TITLE
bug fix

### PR DESCRIPTION
**Pull request by zhangymJLU**
del _id key

### CODE REVIEW

**Comment by rpiazza** [comment]
This is a good fix - @gtback, should we merge in??

**Comment by gtback** [comment]
Thanks, @zhangymJLU .

Before we can merge this, you'll need to sign the Individual Contributor License Agreement (CLA) located [here](https://www.oasis-open.org/resources/open-repositories/cla). If this is a problem, let us know.

**Comment by zhangymJLU** [comment]
OK, I have accepted the license on this page and replay the confirm email now, @gtback.

**Comment by robincover** [comment]
@zhangymJLU  (Yangming Zhang) - Many thanks, and your CLA is now on file.  -rcc

**Pull request merged**
